### ISSUE TITLE
`OpEmitter::assert_unsigned_int32` blows up for `u32` case if values have high(32nd) bit set

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#174] opened 2024-04-18 16:02 UTC
Discovered in #173.

The Rust `a >= b` (both `u32`) translates into the following IR:
https://github.com/0xPolygonMiden/compiler/blob/663b146b45a027770392f7ea76f7144cef34beea/tests/integration/expected/ge_u32.hir#L12-L17

From which the following MASM is generated:
https://github.com/0xPolygonMiden/compiler/blob/663b146b45a027770392f7ea76f7144cef34beea/tests/integration/expected/ge_u32.masm#L659-L670

The `assertz` fails if `a` or `b` have high(32nd) bit set, which is a valid u32 value.

**EDIT**: Can be reproduced by the commented tests mentioning this issue in their comment.
After the fix, these tests should be enabled.

**Comment by greenhat** [comment] 2024-07-02 14:58
@bitwalker I hit it in #225. As a temporary workaround I suggest we disable it and emit nothing when casting to u32.

**Comment by bitwalker** [comment] 2024-07-02 19:19
Just to confirm a detail here: the bit being set is the _32nd_ bit? Or the 31st? 2^32 is _not_ representable as a 32 bit integer, 2^32-1 is the maximum value that will fit in 32 bits.

**Comment by greenhat** [comment] 2024-07-03 05:08
From the `get_inputs` test the value under cast is 4294967280 which is a valid u32 value with the 32nd bit set. But we're expecting the 32nd bit to be zero for u32 at https://github.com/0xPolygonMiden/compiler/blob/59044947746ba79919faabb0c8f8ea52d6006842/codegen/masm/src/codegen/emit/int32.rs#L86

**Comment by bitwalker** [comment] 2024-07-14 02:46
Fixed in #242. The issue is that the wrong types of casts were being used - and more generally, we lacked an appropriate cast operation for reinterpreting bits as different types. 242 implements a new `bitcast` op which does just that, and is now used in all the places where a bitcast is appropriate (i.e. we don't care about preserving the value of the source type).

**Closed by bitwalker** 2024-07-14 02:46 UTC
Labels: bug
